name: "CI: Build Test"

on: [push, pull_request]

env:
    RUN_ID: build.${{ GITHUB.RUN_ID }}
    RUN_NUMBER: build.${{ GITHUB.RUN_NUMBER }}
    SHA: ${{ GITHUB.SHA }}
    MYGET_API_TOKEN: ${{ SECRETS.MYGET_API_TOKEN }}
    GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}

jobs:
  build:
    name: "${{ matrix.config.os }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { windows-latest }
          - { ubuntu-latest }
          - { macos-latest }

        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              submodules: recursive
              fetch-depth: 0

          - name: Setup dotnet 3.1.x sdk
            uses: actions/setup-dotnet@v1.7.2
            with:
                dotnet-version: 3.1

          - name: Setup dotnet 5.0.x sdk
            uses: actions/setup-dotnet@v1.7.2
            with:
                dotnet-version: 5.0.100-preview.7.20366.6

          - name: Check dotnet sdk install
            run: dotnet --info

          - name: Install dependencies
            run: dotnet restore

          - name: Build solution
            run: dotnet build -c Release --no-restore

          - name: Test solution
            run: dotnet test -c Release --no-build --no-restore --verbosity normal

          - name: Pack packages
            run: |
                $LastTag =git describe --tags (git rev-list --tags --max-count=1)
                echo "Last tag is: ${LastTag}"
                $Version = ($LastTag).TrimStart('v').TrimEnd("beta").TrimEnd("preview")
                echo "Publishing version: ${Version}"
                $PackageVersion = ($LastTag).TrimStart('v') + "-" + $env:RUN_NUMBER + "." + $env:SHA.SubString(0, 7)
                echo "Publishing package version: ${PackageVersion}"
                dotnet pack -c Release -o packages /p:PackageVersion=$PackageVersion /p:Version=$Version --no-build
