---
# SPDX-FileCopyrightText: GitHub, Inc. and contributors
# SPDX-License-Identifier: "MIT License"
#
# Copyright (c) 2022GitHub, Inc. and contributors

# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a
# Pull Request, surfacing known-vulnerable versions of the packages declared
# or updated in the PR. Once installed, if the workflow run is marked as
# required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation:
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: "Dependency Review"

on: [pull_request] # yamllint disable-line rule:truthy

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ§° Checkout Source Code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: "Dependency Review"
        uses: actions/dependency-review-action@v3
