name: gh-pages

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2

            - name: brew update-reset
              run: brew update-reset

            - name: brew update
              run: brew update

            - name: Upgrade CMake and ninja
              run: |
                brew upgrade cmake
                brew ls | grep wq ninja | brew install ninja

            - name: Install dependencies with homebrew
              run: |
                brew install graphviz doxygen
                brew ls | grep -wq freetype | brew install freetype
                brew ls | grep -wq python | brew install python
                pip3 install -r docs/requirements.txt

            - name: configure
              run: |
                ls
                cmake -G Ninja -S docs -B ./build
            - name: build
              run: |
                pushd build
                ninja Sphinx
                popd
            - name: gh-pages
              uses: actions/checkout@master
              with:
                  ref: "gh-pages"
                  clean: false
            - name: Move & Commit files
              run: |
                  git config --global user.name github-actions
                  git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
                  rm -rf d* && rm *.html && rm *.svg && rm *.map && rm *.md5 && rm *.png && rm *.js && rm *.css
                  git add .
                  cp -rp ./build/manual/html/* . && rm -rf ./build && ls -lah
                  git add .
                  git commit -m "Documentation for $GITHUB_SHA" ||  true
                  git push --force || true
