---
# SPDX-FileCopyrightText: JÃ¼rgen MÃ¼lbert <juergen.muelbert@outlook.de>
#
# SPDX-License-Identifier: EUPL-1.2
#
name: Processing issues
on:
  issues:
    types: [opened]

jobs:
  fastlane-env:
    name: fastlane env reminder
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "ðŸ§° Check out code"
        uses: actions/checkout@v3

      - name: Send Issue Processing Reminder
        uses: fastlane/github-actions/fastlane-env-reminder@latest
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
