---
# SPDX-FileCopyrightText: Dr. Jan-Philip Gehrcke
#
# SPDX-License-Identifier: Apache-2.0
#

name: github-repo-stats

on: # yamllint disable-line rule:truthy
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: 0 23 * * *
  workflow_dispatch: # Allow for running this manually.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@2387abdb09c714236860ee088c97963665e131a7 # master
        with:
          ghtoken: ${{ secrets.ghrs_github_api_token }}
