---
# SPDX-FileCopyrightText: semgrep
#
# SPDX-License-Identifier: MIT
#

# Name of this GitHub Actions workflow.
name: Semgrep

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release]

  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

  workflow_dispatch:

  schedule:
    - cron: "37 17 * * 4"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  semgrep:
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    container:
      image: returntocorp/semgrep

    steps:
      - name: "ðŸ§° Checkout Source Code"
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run semgrep ci
        run: semgrep ci --sarif --output=semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@b7cec7526559c32f1616476ff32d17ba4c59b2d6 # v3.25.5
        with:
          sarif_file: semgrep.sarif
        if: always()
