---
name: 'Write good'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
      - uses: actions/checkout@v3
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@v1.5
      # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"
      - name: Post comment
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false # This is the default
