---
# SPDX-FileCopyrightText: Tom Ross
#
# SPDX-License-Identifier: MIT
#
name: "Write good"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
      - name: "ðŸ§° Check out code"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@v1

      # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"

      - name: Post comment
        uses: mshick/add-pr-comment@v2
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false # This is the default
