# SPDX-FileCopyrightText: Tom Ross
#
# SPDX-License-Identifier: MIT
#
name: Write good

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release]

  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: ðŸ§° Checkout Source Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@5897a4ff597390bd521c5c3a6c062bf96147a341 # v1.6
      # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"
      - name: Post comment
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false # This is the default
